### ISSUE TITLE
No linux support for terminal-notifier

### ISSUE THREAD

**Issue by danfarrow** [metalelf0/pomodori-todo.txt#6]
I was very excited about running `pom start` for the first time but then I saw the message `terminal-notifier is only supported on Mac OS X 10.8, or higher`

I'm on Ubuntu :(

**Comment by diegoflorez** [comment]
Same happens to me!

**Comment by dcm31** [comment]
would also hope to see this feature

**Comment by metalelf0** [comment]
Ok, I tried hacking a solution using `notify-send` for linux OS. You should try checking out the `feature/linux-terminal-notifier` branch and make sure `notify-send` is installed on your ubuntu. Unfortunately right now I don't have a linux machine for testing, so I'd suggest you to try out my code and give me some feedback. I'll be able to work on a linux machine in the next days! Thank you in advance :)

**Comment by danfarrow** [comment]
hi again, it works! At first I was getting this error:

    /home/dan/bin/pomodori-todo.txt/lib/file_logger.rb:21:in `block in add_separator_if_new_day': 
    undefined method `split' for nil:NilClass (NoMethodError)
	from /home/dan/bin/pomodori-todo.txt/lib/file_logger.rb:21:in `open'
	from /home/dan/bin/pomodori-todo.txt/lib/file_logger.rb:21:in `add_separator_if_new_day'
	from /home/dan/bin/pomodori-todo.txt/lib/file_logger.rb:10:in `notify_start'
	from /home/dan/bin/pomodori-todo.txt/lib/pomo_logger.rb:11:in `log_pomodoro_started'
	from /home/dan/Dropbox/work/todo.txt/actions/pom:82:in `<main>'

Manually creating the file `~/Documents/pomodoro_log.txt`, with one blank line, fixed it. I would like to contribute a fix but I need to improve my Ruby skills first - I would allow 6 pomodoros :)
